[package]
name = "org-hermes-telegram"
version = "0.1.0-dev"
authors = ["Zoran Zaric <zz@zoranzaric.de>"]
edition = "2018"

[dependencies]
frankenstein = "0.4"

log = "0.4"
env_logger = "0.8"
metrics = "0.16"
metrics-exporter-prometheus = "0.5"

ureq = { version = "2", features = [ "json" ] }
